### ISSUE TITLE
Pass CLI parameters to electron

### ISSUE THREAD

**Issue by gknapp** [alex8088/electron-vite#149]
I want to pass CLI parameters to my electron app. I start my dev environment via `npm start` which runs `electron-vite dev`. Custom parameters are not passed on.

My expectation was that I should be able to do this:

`npm start --myparam`

or 

`npm start -- --myparam` (if needed)

And electron would be passed this parameter so in my app code I can use:

```js
if (app.commandLine.hasSwitch("myparam")) {
   // do something different
}
````

### Suggested solution

It looks like electron-vite uses `spawn()` to start electron and only looks for specific arguments (example: remote debugging port) to include:

https://github.com/alex8088/electron-vite/blob/master/src/electron.ts#L124

Could `process.argv` be appended to `args` to pass them through to electron?

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
It is recommended to handle command line via [Env Variables and Modes](https://evite.netlify.app/guide/env-and-mode.html):

- For electron cli command:

```ts
import { app } from 'electron'
if (import.meta.env.MAIN_VITE_LOG === 'true') {
  app.commandLine.appendSwitch('enable-logging', 'electron_debug.log')
}
```

- For app args:

```ts
const param = import.meta.env.MAIN_VITE_MY_PARAM === 'true' || /--myparam/.test(process.argv[2])
```

  1. For development, using ` import.meta.env` and `Modes` to decide whether to use. 
  2. For production (app), using `process.argv` to handle.
  
For now, this is probably the better way to go. Since CLI commands have to be named and exist, so customization doesn't seem to be possible.

**Comment by gknapp** [comment]
Thank you - should this information be added to the docs?

**Comment by mifi** [comment]
created a PR to support this: #339
