### ISSUE TITLE
Unclear installation instructions

### ISSUE THREAD

**Issue by Andrew-web-coder** [alex8088/electron-vite#162]
### Clear and concise description of the problem

I am trying to follow the docs https://evite.netlify.app/guide/, I hoped tgat `npm i electron-vite -D` would do all the magic, but it just add some files. Next command `npm create @quick-start/electron` creates subfolder and it is not clear what is happening, now I have two package.json files, nothing works, and where do I put `"electron-vite dev"` etc?

```
error during preview electron app:
Error: Cannot find module 'electron/package.json'
```

### Suggested solution

Please provide more clear step by step instructions.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
If your project already exists, you can install `electron-vite` and follow the documentation to configure it. 

`npm create @quick-start/electron`  used to create a complete project for quick development.

**Comment by Andrew-web-coder** [comment]
@alex8088 But what does `If your project already exists` mean? Do I have to install electron before electron-vite?

**Comment by TheWashiba** [comment]
@Andrew-web-coder, I'm getting a bit of a "I need 101 tutorial in Electron/TypeScript" sense here and honestly such questions are beyond this projects scope, like adding a detailed explanation "what is Vite and how it works?". This plugin has a very clearly defined scope, goal and features at the beginning of the Readme. I might as well add that I've rarely seen such a beautifully documented 3rd party plugin (kudos to @alex8088 and all the contributors). A PR for doc improvements of course is always welcome if it's within the scope of the project (for ex. explaining how npm scripts work is a bit of an overkill).

**Comment by Andrew-web-coder** [comment]
@TheWashiba All I am asking is a list of commands that I have to execute in order to get fully functional setup. Right now, following the docs results in confusing, non-working setup.

**Comment by TheWashiba** [comment]
I took a look again at the docs. Scaffolding section (which means exactly that we want the automatically working boilerplate, no manual wiring), so as followed:
```
npm create @quick-start/electron
```
Then as follows, the CLI output:
```
Need to install the following packages:
  @quick-start/create-electron@1.0.12
Ok to proceed? (y) y
✔ Project name: … example-electron-project
✔ Select a framework: › react
✔ Add TypeScript? … No / Yes
✔ Add Electron updater plugin? … No / Yes
✔ Enable Electron download mirror proxy? … No / Yes

Scaffolding project in /home/user/Documents/projects/example-electron-project...

Done. Now run:

  cd example-electron-project
  npm install
  npm run dev
``` 
I ran the commands and the following I've got is this:

![image](https://github.com/alex8088/electron-vite/assets/10478970/b703fd19-170d-479b-8fa9-0bedf7596e85)

How could this be improved, because this already looks dead simple?

**Comment by Andrew-web-coder** [comment]
Wait a minute, is that all? So, the command `npm i electron-vite -D` is not needed? It is stated here - https://evite.netlify.app/guide/#installation And this one is not needed, too - https://evite.netlify.app/guide/#command-line-interface ?

**Comment by TheWashiba** [comment]
It's written just right next https://evite.netlify.app/guide/#command-line-interface, that it's a binary that you install here, so it provides some common functionality, but of course the binary needs a config `electron.vite.config.js` for it to know "where is the main entrypoint, renderer, preload script and etc".

However, if you don't want to do the whole manual hassle as it's quite the usual for Electron apps, to wire up things on your own (like, Webpack config, electron-builder config, TypeScript config and etc.), instead you can jump right next to the scaffolding section. I don't know how much you're familiar with Electron, Vite or whatever, but in projects like these, you can assume, that there's the manual way and the "scaffold me some boilerplate" way of doing things.

It's nothing specific to this project, you would go the same pathways by choosing any other Vite, Webpack and etc. tooling. This plugin however, is the most advanced and user friendliest so far from what I've found, since Forge Vite Plugin still doesn't provide out of the box TS support (for the configs and some manual touching is needed for the app code albeit minimal) and some other features.

If you still think there's some better way of writing the Readme, I think the project author would appreciate any suggestions or a PR.

**Comment by Andrew-web-coder** [comment]
@TheWashiba Thank you so much for the explanation! I think you should just add part of your last comment right here - https://evite.netlify.app/guide/#scaffolding-your-first-electron-vite-project - and then everything would be clear.
