### ISSUE TITLE
`Uncaught TypeError: _tmpl$ is not a function` on a fresh installation

### ISSUE THREAD

**Issue by seahindeniz** [alex8088/electron-vite#179]
### Describe the bug

I just followed the installation instructuons on https://evite.netlify.app/guide/#scaffolding-your-first-electron-vite-project 
Here's the terminal output
```bash
❯ pnpm create @quick-start/electron

.../Library/pnpm/store/v3/tmp/dlx-43391  |   +8 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/sahindeniz/Library/pnpm/store/v3
  Virtual store is at:             ../../Library/pnpm/store/v3/tmp/dlx-43391/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-43391  | Progress: resolved 8, reused 7, downloaded 1, added 8, done
✔ Project name: … tempest-local-tools-electron
✔ Select a framework: › solid
✔ Add TypeScript? … No / Yes
✔ Add Electron updater plugin? … No / Yes
✔ Enable Electron download mirror proxy? … No / Yes

Scaffolding project in /Users/sahindeniz/projects/personal/tempest-local-tools-electron...

Done. Now run:

  cd tempest-local-tools-electron
  pnpm install
  pnpm run dev                                                                                                                 39.85s
```

When I ran `pnpm dev` it runs the app. However, the renderer has the following error
![image](https://github.com/alex8088/electron-vite/assets/5789670/c375a391-b55a-43c8-ac4f-c0991bd618c7)

### Electron-Vite Version

1.0.21

### Electron Version

22.3.4

### Vite Version

4.2.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by seahindeniz** [comment]
I just tried other frameworks, including vanilla template, none of them have this issue. Happens only with Solid

**Comment by alex8088** [comment]
@seahindeniz，I can't reproduce this.
![20230531105805](https://github.com/alex8088/electron-vite/assets/25053004/537aa2d6-60a2-44ed-8123-721fecbcda45)

Check your node ver, or remove node_modules and reinstall.

**Comment by seahindeniz** [comment]
It's the same as yours. Bare this in mind, I was using pnpm and as said before, it's a fresh install so a node_modules will be a new one

**Comment by HudsonGraeme** [comment]
I ran into a very similar issue today with a regular solid app (no electron). This app was working perfect about a week ago, and I haven't changed anything since... Now `pnpm dev` leads to a very similar error as posted in your screenshot.

Tried the usual things, removed lockfile, node modules, downgraded pnpm, upgraded pnpm etc but all were to no avail and the app no longer starts :/

<img width="453" alt="image" src="https://github.com/alex8088/electron-vite/assets/25019680/bc7d9368-5f3c-4771-90b2-a3e6571da120">

**Comment by HudsonGraeme** [comment]
I got around this issue by switching `pnpm` out in favor of `yarn`. 

I tried tracking the error down the app by placing `<ErrorBoundary` components everywhere and found that everything in solid router and the UI framework I'm using to be fine - no errors. I was able to move the error boundary down to the main `<Outlet>` component responsible for rendering my custom components and everything beneath that was throwing the same error mentioned in this thread. Since the error boundary was there catching the first error, I could keep the app running and see further errors. Turns out almost every custom component I had rendering would throw that error, which doesn't make sense considering the app is working in production and was working in dev last week without any new changes. :confused:

Not sure if there's an incompatibility between `pnpm` (I certainly can't find any issues around it) but something is definitely awry between the two.

**Comment by alex8088** [comment]
Pnpm is really good, but occasionally there are some puzzling problems.  But not sure if this is the problem caused by pnpm.

**Comment by hy999** [comment]
If you used yarn,it maybe hava an error
When I Use npm,it's ok

**Comment by alex8088** [comment]
- https://github.com/solidjs/vite-plugin-solid/issues/134
- https://github.com/solidjs/solid-refresh/pull/52
